---
- name: delete config/credentials.yml.enc
  become_user: root
  file: 
    state: absent
    path: "{{ item }}"
  loop: 
    - "{{ app_dir }}/config/credentials.yml.enc"
    - "{{ app_dir }}/config/credentials/development.yml.enc"
    - "{{ app_dir }}/config/credentials/production.yml.enc"

- name: check master.key
  stat: 
    path: "{{ app_dir }}/config/master.key"
  register: master_key

# - name: create new credentials.yml.enc and master.key
#   shell: bash -lc 'EDITOR="vi" bin/rails credentials:edit'
#   args: 
#     chdir: "{{ app_dir }}"
#   when: master_key.stat.exists == false

# - name: update credentials.yml.enc
#   blockinfile:
#     dest: "{{ app_dir }}/config/credentials.yml.enc"
#     insertafter: EOF
#     content: |
#       aws:
#         access_key_id: SecretManagerから取得
#         secret_access_key: SecretManagerから取得
#         active_storage_bucket_name: cfn-raisetech
#   when: master_key.stat.exists == false

- name: update config/environments/development.rb
  replace: 
    path: "{{ app_dir }}/config/environments/development.rb"
    regexp: config.active_storage.service = :local
    replace: config.active_storage.service = :amazon

- name: update config/storage.yml
  replace: 
    path: "{{ app_dir }}/config/storage.yml"
    regexp: |
      access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
      secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
      region: ap-northeast-1
      bucket: <%= Rails.application.credentials.dig(:aws, :active_storage_bucket_name) %>
    replace: |
      access_key_id: <%=  %>
      secret_access_key: <%=  %>
      region: ap-northeast-1
      bucket: <%= %>
